export enum ErrorCodes {
  // Reserva
  PENDING_ORDER_EXISTS = "PENDING_ORDER_EXISTS",
  CART_EMPTY = "CART_EMPTY",
  
  // Checkout & Orden
  NO_ACTIVE_RESERVATION = "NO_ACTIVE_RESERVATION",
  RESERVATION_EXPIRED = "RESERVATION_EXPIRED",
  ORDER_EXPIRED = "ORDER_EXPIRED",
  ORDER_NOT_FOUND = "ORDER_NOT_FOUND",
  
  // Pago
  PAYMENT_DATA_INVALID = "PAYMENT_DATA_INVALID",
  INSUFFICIENT_STOCK_FINAL = "INSUFFICIENT_STOCK_FINAL",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  
  // Cancelación
  NOTHING_TO_CANCEL = "NOTHING_TO_CANCEL",
  
  // Sistema
  INTERNAL_ERROR = "INTERNAL_ERROR"
}
